# Generated by Django 3.2 on 2023-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
