# Generated by Django 3.2 on 2023-10-10 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
